import { Contact } from "./interfaces";

export const contacts: Contact[] = [
  {
    id: "1",
    name: "John Doe",
    image: "https://i.pravatar.cc/300",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    lastMessageDate: "Viernes",
  },
  {
    id: "2",
    name: "Jane Doe",
    image: "https://i.pravatar.cc/301",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    lastMessageDate: "Jueves",
  },
  {
    id: "3",
    name: "Tiago Juarez",
    image: "https://i.pravatar.cc/299",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    lastMessageDate: "Martes",
  },
  {
    id: "4",
    name: "Juan Perez",
    image: "https://i.pravatar.cc/400",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    lastMessageDate: "Lunes",
  },
  {
    id: "5",
    name: "Pedro Juarez",
    image: "https://i.pravatar.cc/250",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    lastMessageDate: "Martes",
  },
  {
    id: "6",
    name: "Juan Perez",
    image: "https://i.pravatar.cc/400",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    lastMessageDate: "Lunes",
  },
  {
    id: "6",
    name: "Juan Perez",
    image: "https://i.pravatar.cc/400",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    lastMessageDate: "Lunes",
  },
  {
    id: "6",
    name: "Juan Perez",
    image: "https://i.pravatar.cc/400",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    lastMessageDate: "Lunes",
  },
  {
    id: "6",
    name: "Juan Perez",
    image: "https://i.pravatar.cc/400",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    lastMessageDate: "Lunes",
  },
  {
    id: "6",
    name: "Juan Perez",
    image: "https://i.pravatar.cc/400",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    lastMessageDate: "Lunes",
  },
  {
    id: "6",
    name: "Juan Perez",
    image: "https://i.pravatar.cc/400",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    lastMessageDate: "Lunes",
  },
  {
    id: "6",
    name: "Juan Perez",
    image: "https://i.pravatar.cc/400",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    lastMessageDate: "Lunes",
  },
  {
    id: "6",
    name: "Juan Perez",
    image: "https://i.pravatar.cc/400",
    lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    lastMessageDate: "Lunes",
  },
];
